version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  FULL_CHAIN: ${FULL_CHAIN}
  PRIV_KEY: ${PRIV_KEY}

services:
  ws:
    image: ws:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file:
       - .env
    build:
      context: .
      target: ws
    environment:
      <<: *shared_environment
    ports:
      - '8888:8888'
