version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  FULL_CHAIN: ${FULL_CHAIN}
  PRIV_KEY: ${PRIV_KEY}

services:
  websocket:
    image: websocket:latest
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    env_file:
       - .env
    build:
      context: .
      target: websocket
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
